### ISSUE TITLE
Move the `ExecutionHelper` contract inside `contracts/helpers/`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync_seaport#25]
# Tasks

- [ ] Move `ExecutionHelper.sol` file from `ExecutionHelper/contracts/` to `contracts/helpers/`.
- [ ] Move `ExectionHelper`'s deploy script to `deploy/` or add its deployment to the Seaport deployment script.
- [ ] Update the Makefile as needed.
